plugins {
    id 'eclipse'
    id 'net.minecraftforge.gradle' version '[6.0.52,6.2)'
}

version = '1.0'
base.archivesName = "packloader"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    copyIdeResources = true

    runs {
        client {
            workingDirectory project.file('../run')

            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                jvmArgs += mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.toList()
            }

            mods {
                packloader {
                    source sourceSets.main
                }
            }
        }
    }
}

dependencies {
    minecraft 'net.minecraftforge:forge:${generator.getGeneratorMinecraftVersion()}-${generator.getGeneratorBuildFileVersion()}'
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.ow2.asm:asm-debug-all:5.2'
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.ow2.asm') {
                details.useVersion '5.2'
            }
        }
    }

    exclude group: 'net.minecraftforge', module: 'mergetool'
}