plugins {
    id 'java'
    id 'net.minecraftforge.gradle' version '7.0.36'
    id 'net.minecraftforge.renamer' version '1.1.7'
}

version = '1.0'
base.archivesName = "packloader"

java.toolchain.languageVersion = JavaLanguageVersion.of(8)

minecraft {
    mappings channel: 'snapshot', version: '20171003-1.12'

    runs {
        register('client') {
            def mcreatorJvmOptions = System.getenv('MCREATOR_JVM_OPTIONS')
            if (mcreatorJvmOptions) {
                jvmArgs += mcreatorJvmOptions.split("\\s+").findAll { it.trim() }.toList()
            }
        }

        configureEach {
            workingDir.convention layout.projectDirectory.dir('../run')

            systemProperty 'forge.logging.markers', 'REGISTRIES'
            systemProperty 'forge.logging.console.level', 'debug'
        }
    }
}

repositories {
    minecraft.mavenizer(it)
    maven fg.forgeMaven
    maven fg.minecraftLibsMaven
}

dependencies {
    implementation minecraft.dependency('net.minecraftforge:forge:${generator.getGeneratorMinecraftVersion()}-${generator.getGeneratorBuildFileVersion()}')
}

renamer.mappings.from minecraft.dependency.toSrgFile

renamer.classes(tasks.named('jar', Jar)) {
    archiveClassifier = ''
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8' // Use the UTF-8 charset for Java compilation
}

configurations.configureEach {
    resolutionStrategy {
        force 'org.ow2.asm:asm-debug-all:5.2'
        force 'net.minecraftforge:mergetool:0.2.3.3'
        eachDependency { DependencyResolveDetails details ->
            if (details.requested.group == 'org.ow2.asm') {
                details.useVersion '5.2'
            } else if (details.requested.group == 'net.minecraftforge' && details.requested.name == 'mergetool') {
                details.useVersion '0.2.3.3'
            }
        }
    }
}